- name: swe_agent

  _target_: env.agent_loop.ArlUniAgentLoop

  concurrency: 32
  log_dir: /tmp/swebench_qwen3_coder_nexus
  mask_abnormal_exit_traj: false
  tool_parser: qwen3_coder

  interaction:
    action_timeout: 600
    max_turns: 50

  env:
    deployment:
      type: nexus
      image: python:3.11-slim
      timeout: 3600
      startup_timeout: 1200
    env_variables:
      PIP_PROGRESS_BAR: "off"
      PIP_CACHE_DIR: "~/.cache/pip"
      PAGER: "cat"
      MANPAGER: "cat"
      LESS: "-R"
      TQDM_DISABLE: "1"
      GIT_PAGER: "cat"

  tools:
    - name: str_replace_editor
    - name: execute_bash
    - name: submit

  reward:
    eval_timeout: 600
